# .rubocop.yml

AllCops:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false